channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - matplotlib
    - pandas
    - scipy
    - rise
    - pip:
        - jupyter
        - jupyter-contrib-nbextensions
        - mne
        - scikit-learn
        - seaborn
        - pyriemann
        - versioneer
