name: Docs

on:
  push:
    branches: [ master, 'dev/*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install .
    - name: Build docs
      run: |
        cd doc && make html
