name: Docs

on:
  push:
    branches: [ master, 'dev/*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up ssh access  
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel

        # Install wxPython wheels since they are distribution-specific and therefore not on PyPI
        # See: https://wxpython.org/pages/downloads/index.html
        pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython

        pip install .

    - name: Build docs
      run: |
        git config --global user.email "eeg-notebooks-ci@github.com"
        git config --global user.name "eeg-notebooks github repo CI"
        cd doc && make install
