name: Test

on:
  push:
    branches: [ master, 'dev/*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.os }}, py-${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macOS-latest]
        python_version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install swig
      if: "startsWith(runner.os, 'windows')"
      run: |
        (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.1.zip","swigwin-4.0.1.zip");
        Expand-Archive .\swigwin-4.0.1.zip .;
        echo "$((Get-Item .).FullName)/swigwin-4.0.1" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Setup Display
      if: "startsWith(runner.os, 'Linux')"
      run: |
        sudo apt -y install xvfb libgtk-3-dev freeglut3-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install wxPython
        pip install pyo
        pip install h5py
        pip install . -r requirements.txt
        pip install -e .
    - name: Run eegnb
      if: "startsWith(runner.os, 'Linux')"
      run: |
        Xvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &> xvfb.log &
        export DISPLAY=:0
        echo "first test: print help menu"
        eegnb --help
        echo "second test: runexp with no args"
        eegnb runexp
    #- name: Typecheck
    #  run: |
    #    mypy --ignore-missing-imports
    #- name: Test
    #  run: |
    #    poetry run pytest  # no tests, yet
